### ISSUE TITLE
new 2020 image builds with 'start' config failing to launch on binder or jupyterhub

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks#122]
`2020.02.03-0853dbb` and `latest` tags are not launching on binder or jupyterhubs, seems related to recent changes enabling `start` scripts for onbuild images:
https://github.com/pangeo-data/pangeo-stacks/commits/master/onbuild/r2d_overlay.py 

Here is the traceback from pod logs that get stuck in `CrashLoopBackOff`
```
Traceback (most recent call last):
  File "/usr/local/bin/r2d_overlay.py", line 167, in <module>
    main()
  File "/usr/local/bin/r2d_overlay.py", line 163, in main
    start()
  File "/usr/local/bin/r2d_overlay.py", line 135, in start
    ['/bin/bash', '-c', command], preexec_fn=applicator._pre_exec
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 1552, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```

pinging @rsignell-usgs who encountered this, also @jhamman, @yuvipanda, and @scollis for possible fixes

**Comment by rabernat** [comment]
Could this be the cause of https://github.com/pangeo-data/pangeo-cloud-federation/issues/523?

**Comment by scottyhq** [comment]
closed by https://github.com/pangeo-data/pangeo-stacks/pull/118
